packages:
  - "app"
  - "admin"
  - "server"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: false
  prisma: true
  sharp: false
